### ISSUE TITLE
TPLINK Deco X60 Support Data

### ISSUE THREAD

**Issue by jayg37** [menahishayan/TP-Link-Archer-C50-API#4]
Login
network
Clients
network (multiple clicks)
internet
hamburger->advanced->status
hamburger logout
[TPLINK Deco X60 Support Data.zip](https://github.com/menahishayan/TP-Link-Archer-C50-API/files/5904292/TPLINK.Deco.X60.Support.Data.zip)

**Comment by menahishayan** [comment]
To begin understanding whether or not this model would be supported, let's first try to replicate one of the login HTTP requests.

Send a HTTP **POST** request to your router as follows:
 - **URL:** http://192.168.1.1/cgi-bin/luci/;stok=/login?form=login
 - **Content-Type:** application/json
 - **Origin:** http://192.168.1.1
 - **Referer:** http://192.168.1.1/webpages/index.html
 - **Accept-Encoding:** gzip, deflate
 - **Cookie:** sysauth=e62c693a40da554eb8655d38f6d76b89
 - **Body:**
sign=3c8a92acdf8357d8082d40cafb26e2b9116755d5f73b04ca52c18aa4d0f6ea2b2b0e7f550c278b22fd3969ba98ca5920bd5c70bb14562cdd7976b31ec8b472fc23513609436a5567dbadcd6244302ecbc3de73e03e0507c52c568363cc00125e621c150efade16d265bd84428dd9262bb0872e52a54d59d2cb3e7e5da078ed3e&data=my%2BcJgmY9y8C2TP9xlYGRxfD2VzudzTdC0snUooD7kUN0FNggCzxCaHy73v59b1Qx6zaJS3HS8kRhrmbL%2BgJRqIc6nsuFMe%2FjB3Z%2FM93eBzpO1OOau83vN785DxtMtf6S5JLYvjaQxjO5M6tZqn3LHCGzijvLA1YimF5b86HQHOiOzjxCHdg%2BkbGGK2ofLDSPFQX6ykp91B7Ejkzkkp3puO9pamqNX5UAtMYoqaXgXDIaykawbiaXHTh%2BIGBD%2FeROQBNFFU5r4g2jLYW5XCa4OUi1aBbT3SwlS81Br57IUKxc8Ewjd1XNWv2PteSk6DcLaw7Y287Af1lyCqDNx0DTITquz%2BAdLW0KsFa8vlR0dtfJ%2Fe6cxU4DFj07eHA7LGi8GkDzhM1LXCLaHk9TnPfRA%3D%3D

Please attach your response status, headers, cookies and body

**Comment by jayg37** [comment]
________________________________

**Comment by menahishayan** [comment]
Try the script mentioned in #5 [Comment 2](https://github.com/menahishayan/TP-Link-Archer-C50-API/issues/5#issuecomment-808205203) and comment back here with whether or not the script worked

**Comment by jayg37** [comment]
Modified IP to match my network.
http://192.168.1.1/webpages/js/su/data/data.min.1601019620091.js

Pasted into web browser and received:
The requested URL /webpages/js/su/data/data.min.1601019620091.js was not found on this server.
________________________________

**Comment by jayg37** [comment]
Entered my info and ran the script on my windows PC. No errors but not much in the vein of results either...I guess it worked. CMD window popped up for half a second.
________________________________

**Comment by menahishayan** [comment]
Please run in the script in a way where you can monitor the output. You need to ensure that MAC Addresses are being displayed.

**Comment by jayg37** [comment]
[C6] Loading wireless clients...
Retrieving auth tokens...
Couldn't fetch auth tokens! Response was: %s {"data":""}
An unknown error happened while fetching data
Logging out of router admin interface...
Traceback (most recent call last):
  File "C:\Users\m_gra\Desktop\c6_test.py", line 133, in <module>
    c6.scan_devices()
  File "C:\Users\m_gra\Desktop\c6_test.py", line 45, in scan_devices
    print(self.last_results.keys())
AttributeError: 'C6' object has no attribute 'last_results'
________________________________

**Comment by AlexandrErohin** [comment]
@jayg37 If you are still looking for a client for Deco X60 - I have the client which supports it https://github.com/AlexandrErohin/TP-Link-Archer-C6U
